# Data Cleaning

Here we will Clean the Mster's data that we have collected so far and format it into what we need for statistical analysis

Loading in our packages:

In [7]:
import pandas as pd
import numpy as np
import scipy

In [31]:
masters_df = pd.read_csv("C:\Personal Projects\masters_players.csv")

masters_df.head(10)

   Year Pos          Name    R1    R2    R3    R4  Total Score Total Par
0  2025   1     R McIlroy  72.0  66.0  66.0  73.0        277.0       -11
1  2025   2        J Rose  65.0  71.0  75.0  66.0        277.0       -11
2  2025   3        P Reed  71.0  70.0  69.0  69.0        279.0        -9
3  2025   4   S Scheffler  68.0  71.0  72.0  69.0        280.0        -8
4  2025  T5          S Im  71.0  70.0  71.0  69.0        281.0        -7
5  2025  T5  B DeChambeau  69.0  68.0  69.0  75.0        281.0        -7
6  2025   7       L Åberg  68.0  73.0  69.0  72.0        282.0        -6
7  2025  T8  X Schauffele  73.0  69.0  70.0  71.0        283.0        -5
8  2025  T8     Z Johnson  72.0  74.0  66.0  71.0        283.0        -5
9  2025  T8         J Day  70.0  70.0  71.0  72.0        283.0        -5

Mutating Pos column (We need to change our ties so that we drop the "T")

In [32]:
masters_df["Pos"] = masters_df["Pos"].str.replace(r"^T", "", regex = True)

masters_df["Pos"].head(30)

0      1
1      2
2      3
3      4
4      5
5      5
6      7
7      8
8      8
9      8
10     8
11    12
12    12
13    14
14    14
15    14
16    14
17    14
18    14
19    14
20    21
21    21
22    21
23    21
24    21
25    21
26    27
27    27
28    29
29    29
Name: Pos, dtype: object

Now We need to create another column "Made Cut" based on whether or not a player made the cut that respective year

In [33]:
masters_df["Made_Cut"] = np.where(masters_df["Pos"] == "MC", 0, 1)

masters_df["Made_Cut"].head(70)

0     1
1     1
2     1
3     1
4     1
     ..
65    0
66    0
67    0
68    0
69    0
Name: Made_Cut, Length: 70, dtype: int32

In [34]:
masters_df.head(20)

,Year,Pos,Name,R1,R2,R3,R4,Total Score,Total Par,Made_Cut
0,2025,1,R McIlroy,72.0,66.0,66.0,73.0,277.0,-11,1
1,2025,2,J Rose,65.0,71.0,75.0,66.0,277.0,-11,1
2,2025,3,P Reed,71.0,70.0,69.0,69.0,279.0,-9,1
3,2025,4,S Scheffler,68.0,71.0,72.0,69.0,280.0,-8,1
4,2025,5,S Im,71.0,70.0,71.0,69.0,281.0,-7,1
5,2025,5,B DeChambeau,69.0,68.0,69.0,75.0,281.0,-7,1
6,2025,7,L Åberg,68.0,73.0,69.0,72.0,282.0,-6,1
7,2025,8,X Schauffele,73.0,69.0,70.0,71.0,283.0,-5,1
8,2025,8,Z Johnson,72.0,74.0,66.0,71.0,283.0,-5,1
9,2025,8,J Day,70.0,70.0,71.0,72.0,283.0,-5,1
10,2025,8,C Conners,68.0,70.0,70.0,75.0,283.0,-5,1
11,2025,12,H English,70.0,73.0,73.0,68.0,284.0,-4,1
12,2025,12,M Homa,74.0,70.0,69.0,71.0,284.0,-4,1
13,2025,14,B Watson,71.0,72.0,74.0,68.0,285.0,-3,1
14,2025,14,J Rahm,75.0,71.0,70.0,69.0,285.0,-3,1
15,2025,14,J Spieth,73.0,73.0,69.0,70.0,285.0,-3,1
16,2025,14,T Hatton,69.0,70.0,75.0,71.0,285.0,-3,1
17,2025,14,M McCarty,71.0,68.0,75.0,71.0,285.0,-3,1
18,2025,14,T Hoge,72.0,72.0,70.0,71.0,285.0,-3,1
19,2025,14,C Morikawa,72.0,69.0,72.0,72.0,285.0,-3,1

Let's also mutate everyone who missed cuts or round scores say to illness/injury, dq's etc to NA's for data analysis

In [35]:
masters_df["R1"] = masters_df["R1"].replace("", np.nan)
masters_df["R2"] = masters_df["R2"].replace("", np.nan)
masters_df["R3"] = masters_df["R3"].replace("", np.nan)
masters_df["R4"] = masters_df["R4"].replace("", np.nan)
masters_df["Total Score"] = masters_df["Total Score"].replace("", np.nan)
masters_df["Total Par"] = masters_df["Total Par"].replace("", np.nan)

Now let's start changing data types: we know the year should be a date, the names should be string, and all of the scores should be numeric

In [36]:
masters_df["Pos"] = masters_df["Pos"].astype("category")

masters_df["Year"] = masters_df["Year"].astype(int)

masters_df["Name"] = masters_df["Name"].astype("string")

masters_df["R1"] = pd.to_numeric(masters_df["R1"])

masters_df["R2"] = pd.to_numeric(masters_df["R2"])

masters_df["R3"] = pd.to_numeric(masters_df["R3"])

masters_df["R4"] = pd.to_numeric(masters_df["R4"])

masters_df["Total Score"] = pd.to_numeric(masters_df["Total Score"])

masters_df["Total Par"] = (masters_df["Total Par"].replace("E", 0))

masters_df["Total Par"] = pd.to_numeric(masters_df["Total Par"])

masters_df["Made_Cut"] = pd.to_numeric(masters_df["Made_Cut"])


masters_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7299 entries, 0 to 7298
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Year         7299 non-null   int32
 1   Pos          7298 non-null   category
 2   Name         7299 non-null   string
 3   R1           7258 non-null   float64
 4   R2           7178 non-null   float64
 5   R3           4666 non-null   float64
 6   R4           4620 non-null   float64
 7   Total Score  7250 non-null   float64
 8   Total Par    5335 non-null   float64
 9   Made_Cut     7299 non-null   int32
dtypes: category(1), float64(6), int32(2), string(1)
memory usage: 466.1 KB

Now let's output the csv as our finalized masters participants

In [37]:
masters_df.to_csv("C:/Personal Projects/finalized_masters_participants.csv", index=False)

In [38]:
masters_df[["R1", "R2", "R3", "R4"]].isna().sum()

R1      41
R2     121
R3    2633
R4    2679
dtype: int64